// ============================================
// NetXpert AI - تصدير نتائج الحاسبة كملف PDF
// يستخدم مكتبة jsPDF (محمّلة عبر CDN بملف index.html)
// ============================================

let latestResult = null; // آخر نتيجة حساب (IPv4 أو IPv6) نحتفظ فيها للتصدير

document.addEventListener('subnetResult', (e) => {
    latestResult = e.detail; // { type: 'ipv4' | 'ipv6', data: {...} }

    const exportBtn = document.getElementById('exportPdfBtn');
    if (exportBtn) {
        exportBtn.addEventListener('click', exportResultAsPdf);
    }
});

function buildIPv4Rows(data) {
    return [
        ['IP Address', data.ip],
        ['Subnet Mask', `${data.subnetMask} (/${data.cidr})`],
        ['Network Address', data.networkAddress],
        ['Broadcast Address', data.broadcastAddress],
        ['First Usable Host', data.firstHost],
        ['Last Usable Host', data.lastHost],
        ['Total Addresses', data.totalHosts.toLocaleString()],
        ['Usable Hosts', data.usableHosts.toLocaleString()],
        ['Address Class', data.ipClass],
        ['Address Type', data.isPrivate ? 'Private' : 'Public']
    ];
}

function buildIPv6Rows(data) {
    return [
        ['IPv6 Address', data.ip],
        ['Prefix Length', `/${data.prefix}`],
        ['Network Address', data.networkAddress],
        ['Last Address in Range', data.lastAddress],
        ['Total Addresses', data.totalAddresses],
        ['Address Type', data.addressType]
    ];
}

function exportResultAsPdf() {
    if (!latestResult) return;

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const { type, data } = latestResult;
    const rows = type === 'ipv6' ? buildIPv6Rows(data) : buildIPv4Rows(data);

    // العنوان
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42);
    doc.text('NetXpert AI - Subnetting Report', 14, 20);

    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Report type: ${type === 'ipv6' ? 'IPv6' : 'IPv4'} Subnetting`, 14, 28);
    doc.text(`Generated: ${new Date().toLocaleString('en-US')}`, 14, 34);

    // الجدول (بدون مكتبة autotable، رسم يدوي بسيط عشان ما نحتاج تحميل مكتبة إضافية)
    let y = 46;
    const labelX = 14;
    const valueX = 90;
    const rowHeight = 9;

    doc.setFontSize(10);
    rows.forEach((row, i) => {
        if (i % 2 === 0) {
            doc.setFillColor(241, 245, 249);
            doc.rect(12, y - 6, 186, rowHeight, 'F');
        }
        doc.setTextColor(71, 85, 105);
        doc.text(String(row[0]), labelX, y);
        doc.setTextColor(15, 23, 42);
        doc.text(String(row[1]), valueX, y);
        y += rowHeight;
    });

    // تذييل بسيط
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text('Generated by NetXpert AI - Networking Learning Platform', 14, y + 10);

    const fileName = `NetXpert-Subnet-${data.ip.replace(/[:.]/g, '-')}.pdf`;
    doc.save(fileName);
}
